import { themeStyles } from "./theme";

export const driveStyles = String.raw`
${themeStyles}
.topbar{background:#fff;border-bottom:1px solid var(--line)}.topbar-inner{max-width:1168px;margin:auto;padding:20px 32px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:12px;font-size:17px;font-weight:750;letter-spacing:-.5px}.brand-icon{display:grid;place-items:center;background:var(--green);color:white;width:38px;height:38px;border-radius:12px}.brand-icon svg{width:24px;height:24px}.brand .brand-secondary{font-weight:450;color:var(--muted)}.account{display:flex;align-items:center;gap:9px;color:var(--muted);max-width:40%;font-size:13px}.avatar{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;background:var(--mint);color:var(--green);font-weight:700;flex-shrink:0}.account-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.shell{max-width:1168px;margin:auto;padding:42px 32px 32px}.intro{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:28px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:1.8px;color:var(--green);font-weight:750;margin:0 0 9px}h1{font-size:34px;line-height:1.2;letter-spacing:-1.1px;margin:0 0 10px;font-weight:730}.subtitle{margin:0;color:var(--muted);max-width:580px}.connection{display:inline-flex;align-items:center;gap:7px;color:var(--green);background:var(--mint);padding:6px 11px;border-radius:20px;white-space:nowrap;font-size:12px}.dot{height:6px;width:6px;border-radius:50%;background:currentColor}
.stats{display:grid;grid-template-columns:1.45fr 1fr 1fr;gap:16px;margin-bottom:28px}.stat{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:21px 23px;min-width:0}.stat-title{display:flex;align-items:center;justify-content:space-between;gap:8px;color:var(--muted);font-size:12px;margin-bottom:12px}.stat-title svg{width:17px;height:17px}.stat-value{font-size:26px;font-weight:700;letter-spacing:-.7px;line-height:1.3}.stat-value small{font-weight:400;color:var(--muted);font-size:13px;letter-spacing:0}.stat-note{font-size:12px;color:var(--muted);margin-top:7px}.meter{height:5px;background:#eaf0eb;border-radius:8px;overflow:hidden;margin-top:15px}.meter-fill{height:100%;background:var(--green);border-radius:8px;transition:width .25s}.stat-date{font-size:19px;letter-spacing:-.3px;padding-top:4px}
.files-panel{background:white;border:1px solid var(--line);border-radius:var(--radius);overflow:hidden}.panel-heading{display:flex;align-items:center;justify-content:space-between;padding:22px 24px 17px;gap:16px}.panel-title{display:flex;align-items:center;gap:10px}h2{font-size:17px;font-weight:650;margin:0;letter-spacing:-.3px}.count{display:inline-block;min-width:25px;text-align:center;padding:2px 7px;border-radius:7px;background:var(--mint);color:var(--green);font-size:12px;font-weight:600}.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:9px 14px;border:1px solid var(--line);background:white;border-radius:var(--radius-control);line-height:1.35;color:var(--ink);transition:background .15s,border-color .15s;min-height:39px;font-weight:550;font-size:13px}.btn:hover{background:#f2f6f2;border-color:#c7d6cc}.btn svg{width:16px;height:16px}.btn-quiet{border-color:transparent;background:transparent;color:var(--muted)}.btn-danger{color:var(--red);background:var(--red-bg);border-color:transparent}.btn-danger:hover{background:#fce4df;border-color:#e9bfb6}.btn-primary{background:var(--green);color:white;border-color:var(--green)}.btn-primary:hover{background:#0b513c;border-color:#0b513c}.btn-remove{background:var(--red);border-color:var(--red);color:white}.btn-remove:hover{background:#922a29;border-color:#922a29}
.toolbar{display:flex;gap:12px;align-items:center;padding:0 24px 20px}.search{display:flex;align-items:center;gap:9px;border:1px solid var(--line);border-radius:var(--radius-control);background:#fafbf9;padding:0 12px;flex:1;min-width:0}.search svg{width:18px;color:var(--muted)}.search input{width:100%;border:0;background:transparent;color:var(--ink);padding:11px 0;outline:none;min-width:0}.search:focus-within{outline:3px solid #c8e0d4;outline-offset:1px}.search input:focus-visible{outline:none}.search input::placeholder{color:#7c8c84}select{border:1px solid var(--line);border-radius:var(--radius-control);background:white;color:var(--muted);padding:11px 30px 11px 12px;max-width:200px}.visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.list-heading,.file-row{display:grid;grid-template-columns:minmax(0,1fr) 90px 126px 182px;gap:20px;align-items:center;padding:16px 24px}.list-heading{padding-top:11px;padding-bottom:11px;background:#f8faf7;border-top:1px solid var(--line);border-bottom:1px solid var(--line);color:var(--muted);font-size:11px;font-weight:600}.list-heading span:last-child{text-align:right}.file-row{border-bottom:1px solid #edf0eb;min-height:85px;transition:background .15s}.file-row:last-child{border-bottom:0}.file-row:hover{background:#fbfcfa}.file-row[aria-busy=true]{background:#f5f9f5}.file-main{display:flex;align-items:center;gap:13px;min-width:0}.file-icon{width:40px;height:44px;border-radius:11px;display:grid;place-items:center;background:#edf3ed;color:var(--green);flex-shrink:0}.file-icon[data-kind=archive]{background:#fbf2e3;color:#a77927}.file-icon[data-kind=data]{background:#edf0fa;color:#5d6dae}.file-label{min-width:0}.file-name{font-size:13px;font-weight:600;margin:0;overflow-wrap:anywhere;line-height:1.45}.file-path{font-size:11px;color:var(--muted);margin-top:3px;overflow-wrap:anywhere}.file-size,.file-date{color:var(--muted);font-size:12px}.file-actions{display:flex;gap:5px;justify-content:flex-end}.file-state{display:block;font-size:11px;color:#8e6523;margin-top:5px}.file-row[data-state=error] .file-state{color:var(--red)}.panel-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:14px 24px;background:#fcfdfb;border-top:1px solid var(--line);font-size:11px;color:var(--muted)}.empty{text-align:center;padding:52px 24px}.empty-icon{display:grid;place-items:center;width:54px;height:54px;background:var(--mint);color:var(--green);border-radius:16px;margin:0 auto 18px}.empty h3{font-size:17px;margin:0 0 8px}.empty p{font-size:13px;color:var(--muted);max-width:390px;margin:0 auto;line-height:1.7}.footnote{display:flex;align-items:center;justify-content:center;gap:7px;font-size:11px;color:#75857d;margin-top:24px}.footnote svg{width:13px;height:13px}
.toast{position:fixed;bottom:26px;left:50%;transform:translateX(-50%);display:flex;gap:10px;align-items:center;background:var(--ink);color:white;box-shadow:0 8px 30px #18332d26;padding:14px 16px;border-radius:12px;z-index:50;width:max-content;max-width:calc(100% - 32px);font-size:13px}.toast[data-type=error]{background:#862f2f}.toast[data-type=pending]{background:#70531d}.toast button{border:0;background:none;color:inherit;padding:4px;cursor:pointer;line-height:1}.toast button svg{width:15px;height:15px}.toast p{margin:0;overflow-wrap:anywhere}.spinner{display:inline-block;width:14px;height:14px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spin .8s linear infinite;flex-shrink:0}@keyframes spin{to{transform:rotate(360deg)}}
dialog{border:1px solid var(--line);border-radius:var(--radius-dialog);padding:28px;color:var(--ink);width:calc(100% - 40px);max-width:410px;box-shadow:var(--shadow-dialog)}dialog::backdrop{background:#14332966;backdrop-filter:blur(3px)}.dialog-icon{background:var(--red-bg);color:var(--red);width:46px;height:46px;display:grid;place-items:center;border-radius:14px;margin-bottom:17px}dialog h2{font-size:22px;letter-spacing:-.6px}dialog p{color:var(--muted);line-height:1.7;margin:12px 0}.delete-name{display:block;color:var(--ink);background:#f5f7f3;border:1px solid var(--line);border-radius:var(--radius-control);padding:10px 12px;margin:16px 0;font-size:13px;overflow-wrap:anywhere}.dialog-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:25px}.dialog-actions .btn{padding:10px 17px}
@media(min-width:1200px){.shell{padding-top:48px}}@media(max-width:800px){.shell{padding:28px 20px}.topbar-inner{padding:17px 20px}.stats{gap:10px}.stat{padding:17px}.stat-value{font-size:23px}.list-heading,.file-row{grid-template-columns:minmax(0,1fr) 75px 166px;gap:12px;padding-left:20px;padding-right:20px}.list-heading .date-heading,.file-date{display:none}.file-actions .btn{padding:8px 10px}.stat-date{font-size:17px}}
@media(max-width:560px){.topbar-inner{padding:16px}.brand{font-size:15px;gap:9px}.brand .brand-secondary{display:none}.account{max-width:44%}.shell{padding:26px 16px}.intro{align-items:flex-start;gap:10px;margin-bottom:22px}h1{font-size:29px}.subtitle{font-size:12px}.connection{display:none}.stats{grid-template-columns:1.4fr 1fr;gap:10px;margin-bottom:20px}.stat:last-child{display:none}.stat{padding:16px}.stat-value{font-size:22px}.stat-value small{display:block;font-size:11px;margin-top:3px}.stat-note{font-size:11px}.stat-title{font-size:11px}.panel-heading{padding:18px 16px 14px}.panel-title h2{font-size:16px}.toolbar{padding:0 16px 16px;flex-wrap:wrap;gap:10px}.search{flex-basis:100%}select{max-width:none;width:100%;font-size:12px;padding:9px 12px}.list-heading{display:none}.file-row{display:flex;flex-wrap:wrap;padding:17px 16px;gap:10px 16px}.file-main{width:100%;gap:10px}.file-icon{width:36px;height:40px}.file-size{margin-left:46px}.file-actions{margin-left:auto}.file-actions .btn{min-height:40px;padding:8px 12px}.panel-footer{padding:12px 16px;font-size:10px}.footnote{font-size:10px}.toast{bottom:16px;font-size:12px;max-width:calc(100% - 24px)}.btn{font-size:12px}.empty{padding:42px 18px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}

/* Compact layout; keep the shared theme and touch targets. */
.shell{padding-top:24px}.topbar-inner{padding-block:12px}.intro{margin-bottom:18px}h1{font-size:28px;margin-bottom:6px}.eyebrow{margin-bottom:5px}.stats{margin-bottom:18px;gap:12px}.stat{padding:14px 18px}.stat-title{margin-bottom:6px}.stat-value{font-size:22px}.stat-note{margin-top:4px}.meter{margin-top:9px}.stat-date{font-size:16px}.panel-heading{padding:16px 20px 12px}.toolbar{padding:0 20px 14px}.backup-filters{display:flex;gap:6px;padding:0 20px 12px}.backup-filters .btn{min-height:34px;padding:7px 12px;background:transparent;color:var(--muted);border-color:transparent}.backup-filters .btn[aria-pressed=true]{background:var(--mint);color:var(--green)}.file-row{min-height:66px;padding-block:10px}.file-icon{width:32px;height:36px}.list-heading,.file-row{grid-template-columns:minmax(0,1fr) 90px 145px 182px;gap:14px}.file-path{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-date{font-size:11px}.pagination{display:flex;align-items:center;gap:10px;white-space:nowrap}.pagination .btn{padding:6px 10px;min-height:34px}.panel-footer{padding:10px 20px}.footnote{margin-top:14px}
@media(max-width:800px){.list-heading,.file-row{grid-template-columns:minmax(0,1fr) 75px 166px}.shell{padding-top:20px}.stat{padding:12px 14px}}
@media(max-width:560px){.shell{padding:18px 16px}.intro{margin-bottom:14px}h1{font-size:25px}.stats{margin-bottom:14px}.stat{padding:12px}.stat-title{font-size:11px}.stat-value{font-size:20px}.panel-heading{padding:14px 16px 10px}.backup-filters{padding:0 16px 10px;gap:2px}.backup-filters .btn{min-height:40px;padding-inline:10px}.toolbar{padding:0 16px 12px}.file-row{padding:12px 16px;gap:6px 12px}.file-icon{width:30px;height:34px}.file-size{margin-left:40px}.file-date{display:block;margin-left:40px;font-size:10px}.file-actions{margin-left:auto}.panel-footer{padding:10px 16px;flex-wrap:wrap}.panel-footer #sync-note{display:none}.pagination .btn{min-height:40px}}
@media(max-width:560px){.file-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:3px 10px}.file-main{grid-column:1/-1}.file-size{margin-left:40px;grid-column:1;grid-row:2}.file-date{margin-left:40px;grid-column:1;grid-row:3;white-space:nowrap;font-size:9px}.file-actions{grid-column:2;grid-row:2/4;align-self:center}.file-actions .btn{padding:8px 9px}}

/* Sidebar and main share the same flow on narrow screens. */
.shell{display:grid;grid-template-columns:230px minmax(0,1fr);gap:24px;max-width:1440px;padding:24px 28px}.topbar-inner{max-width:1440px;padding-inline:28px}.drive-main{min-width:0}.drive-sidebar{align-self:start;position:sticky;top:20px;min-width:0}.sidebar-label{font-size:11px;font-weight:650;text-transform:uppercase;letter-spacing:1.5px;color:var(--muted);margin:4px 12px 12px}.drive-sidebar .backup-filters{display:grid;padding:0;gap:4px;margin-bottom:20px}.drive-sidebar .backup-filters .btn{justify-content:flex-start;padding:12px 14px;min-height:42px}.drive-sidebar .stats{display:grid;grid-template-columns:1fr;gap:10px;margin:0}.drive-sidebar .stat{padding:16px}.drive-sidebar .stat-value{font-size:21px}.drive-sidebar .stat-value small{display:block;font-size:12px;margin-top:3px}.drive-sidebar .stat-date{font-size:14px}.drive-main .intro{margin:0 0 20px}.drive-main .subtitle{font-size:13px}.drive-main .file-row,.drive-main .list-heading{grid-template-columns:minmax(0,1fr) 80px 132px 165px;gap:12px;padding-inline:20px}.drive-main .file-actions .btn{padding-inline:10px}.drive-main .panel-footer{flex-wrap:wrap}
@media(min-width:801px) and (max-width:1150px){.shell{grid-template-columns:200px minmax(0,1fr);gap:18px;padding:20px}.drive-main .file-row,.drive-main .list-heading{grid-template-columns:minmax(0,1fr) 70px 155px}.drive-main .file-date,.drive-main .date-heading{display:none}.drive-main .toolbar{flex-wrap:wrap}.drive-main .search{flex-basis:100%}}
@media(max-width:800px){.shell{display:flex;flex-direction:column;gap:18px;padding:18px 16px}.topbar-inner{padding-inline:16px}.drive-sidebar{position:static;width:100%}.sidebar-label{display:none}.drive-sidebar .backup-filters{display:flex;margin-bottom:12px;gap:4px}.drive-sidebar .backup-filters .btn{flex:1;justify-content:center;padding:10px 6px}.drive-sidebar .stats{grid-template-columns:1.4fr 1fr;gap:10px}.drive-sidebar .stat{padding:12px}.drive-sidebar .stat:last-child{display:none}.drive-sidebar .stat-title{margin-bottom:4px}.drive-sidebar .stat-note{font-size:11px}.drive-main .intro{margin-bottom:14px}.drive-main .file-row,.drive-main .list-heading{grid-template-columns:minmax(0,1fr) 75px 166px}}
@media(max-width:560px){.drive-main .file-row{grid-template-columns:minmax(0,1fr) auto;padding:12px 16px;gap:3px 10px}.drive-main .file-date{display:block}.drive-main .intro .eyebrow{display:none}.drive-main .intro h1{font-size:23px}.drive-main .file-actions .btn{padding-inline:9px}}

/* Share desktop grid rows so sidebar and file panel end at the same baseline. */
@media(min-width:801px){.shell{row-gap:18px}.drive-main{display:contents}.drive-main .intro{grid-column:2;grid-row:1;margin:0}.drive-main .files-panel{grid-column:2;grid-row:2;display:flex;flex-direction:column;min-width:0}.drive-main .panel-footer{margin-top:auto}.drive-main .footnote{grid-column:2;grid-row:3;margin:0}.drive-main noscript{grid-column:2}.drive-sidebar{grid-column:1;grid-row:1 / 3;position:static;align-self:stretch;display:flex;flex-direction:column}.drive-sidebar .stats{margin-top:auto}.drive-sidebar .backup-filters{flex-shrink:0}}
`;
